name: sync-package
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: coderzhaoziwei/github-action-package-sync@main
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: run
        run: |
          REPO_INFO=($(echo $GITHUB_REPOSITORY | tr "/" "\n"))
          echo ${REPO_INFO}
          USERNAME=${REPO_INFO[0]}
          DESCRIPTION=`jq -r '.description' package.json`
          echo "$DESCRIPTION"
          echo "${{ secrets }}"
          echo "${{ secrets.GITHUB_ACCESS_TOKEN }}"
          curl \
            -X PATCH \
            -u username:token
            -H "Accept: application/vnd.github.v3+json" \
            -u coderzhaoziwei:${{ secrets.GITHUB_ACCESS_TOKEN }} \
            ${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY} \
            -d '{"description":"$DESCRIPTION"}' \


# WEBSITE=`jq -r ".homepage" package.json`
# TOPICS=`jq ".keywords" package.json`
