name: sync-package
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ github.api.url }}
      # - uses: coderzhaoziwei/github-action-package-sync@main
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: run
        run: |
          curl --request PATCH \
          --header "Accept: application/vnd.github.v3+json" \
          --user ${{ github.repository_owner }}:${{ github.token }} \
          https://api.github.com/repos/${{ github.repository }} \
          --data '{ "description": "This is a description." }'



# DESCRIPTION=`jq -r '.description' package.json`
# REPO_INFO=($(echo $GITHUB_REPOSITORY | tr "/" "\n"))
# echo ${REPO_INFO}
# USERNAME=${REPO_INFO[0]}

# - name: run2
#   run: |
#     curl --request POST \
#     --url https://api.github.com/repos/${{ github.repository }}/issues \
#     --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
#     --header 'content-type: application/json' \

# 字符串仓库所有者的名称。 例如 Codertocat。
# WEBSITE=`jq -r ".homepage" package.json`
# TOPICS=`jq ".keywords" package.json`
